// <auto-generated />
using System;
using BackOfficeMiniProject.DataAccess.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackOfficeMiniProjectCross.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
    partial class BackOfficeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackOfficeMiniProject.DataAccess.DataModels.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("BackOfficeMiniProject.DataAccess.DataModels.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeReceived")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BackOfficeMiniProject.DataAccess.DataModels.Order", b =>
                {
                    b.HasOne("BackOfficeMiniProject.DataAccess.DataModels.Brand", "Brand")
                        .WithMany("Orders")
                        .HasForeignKey("BrandId");
                });
#pragma warning restore 612, 618
        }
    }
}
